name: Deploy Appointment Service

on:
  push:
    branches:
      - main
    paths:
      - 'appointment-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Appointment
        run: dotnet publish ./appointment-service/src/MediBook.Appointment.API/MediBook.Appointment.API.csproj -c Release -o ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: medibook-appointment
          publish-profile: ${{ secrets.APPOINTMENT_PUBLISH_PROFILE }}
          package: ./publish